/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "RANAP-IEs"
 * 	found in "../../asn1/ranap/RANAP-IEs.asn"
 * 	`asn1c -fcompound-names -R`
 */

#ifndef	_RANAP_PLMNs_in_shared_network_H_
#define	_RANAP_PLMNs_in_shared_network_H_


#include <asn_application.h>

/* Including external dependencies */
#include <osmocom/ranap/RANAP_PLMNs-in-shared-network-Value.h>
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>

#ifdef __cplusplus
extern "C" {
#endif

/* RANAP_PLMNs-in-shared-network */
typedef struct RANAP_PLMNs_in_shared_network {
	A_SEQUENCE_OF(RANAP_PLMNs_in_shared_network_Value_t) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} RANAP_PLMNs_in_shared_network_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_RANAP_PLMNs_in_shared_network;

#ifdef __cplusplus
}
#endif

#endif	/* _RANAP_PLMNs_in_shared_network_H_ */
#include <asn_internal.h>
