/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "HNBAP-IEs"
 * 	found in "../../asn1/hnbap/HNBAP-IEs.asn"
 * 	`asn1c -R -fcompound-names`
 */

#ifndef	_HNBAP_BackoffTimer_H_
#define	_HNBAP_BackoffTimer_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* HNBAP_BackoffTimer */
typedef long	 HNBAP_BackoffTimer_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_HNBAP_BackoffTimer;
asn_struct_free_f HNBAP_BackoffTimer_free;
asn_struct_print_f HNBAP_BackoffTimer_print;
asn_constr_check_f HNBAP_BackoffTimer_constraint;
ber_type_decoder_f HNBAP_BackoffTimer_decode_ber;
der_type_encoder_f HNBAP_BackoffTimer_encode_der;
xer_type_decoder_f HNBAP_BackoffTimer_decode_xer;
xer_type_encoder_f HNBAP_BackoffTimer_encode_xer;
per_type_decoder_f HNBAP_BackoffTimer_decode_uper;
per_type_encoder_f HNBAP_BackoffTimer_encode_uper;
per_type_decoder_f HNBAP_BackoffTimer_decode_aper;
per_type_encoder_f HNBAP_BackoffTimer_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _HNBAP_BackoffTimer_H_ */
#include <asn_internal.h>
