/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "HNBAP-IEs"
 * 	found in "../../asn1/hnbap/HNBAP-IEs.asn"
 * 	`asn1c -R -gen-PER`
 */

#ifndef	_HNBAP_NeighbourCellIdentityList_H_
#define	_HNBAP_NeighbourCellIdentityList_H_


#include <asn_application.h>

/* Including external dependencies */
#include <osmocom/hnbap/HNBAP_NeighbourIdentity.h>
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>

#ifdef __cplusplus
extern "C" {
#endif

/* HNBAP_NeighbourCellIdentityList */
typedef struct HNBAP_NeighbourCellIdentityList {
	A_SEQUENCE_OF(HNBAP_NeighbourIdentity_t) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} HNBAP_NeighbourCellIdentityList_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_HNBAP_NeighbourCellIdentityList;

#ifdef __cplusplus
}
#endif

#endif	/* _HNBAP_NeighbourCellIdentityList_H_ */
#include <asn_internal.h>
