/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "HNBAP-IEs"
 * 	found in "../../asn1/hnbap/HNBAP-IEs.asn"
 * 	`asn1c -R`
 */

#ifndef	_HNBAP_GeographicalLocation_H_
#define	_HNBAP_GeographicalLocation_H_


#include <asn_application.h>

/* Including external dependencies */
#include <osmocom/hnbap/HNBAP_GeographicalCoordinates.h>
#include <osmocom/hnbap/HNBAP_AltitudeAndDirection.h>
#include <osmocom/hnbap/HNBAP_IE-Extensions.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* HNBAP_GeographicalLocation */
typedef struct HNBAP_GeographicalLocation {
	HNBAP_GeographicalCoordinates_t	 geographicalCoordinates;
	HNBAP_AltitudeAndDirection_t	 altitudeAndDirection;
	HNBAP_IE_Extensions_t	*iE_Extensions	/* OPTIONAL */;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} HNBAP_GeographicalLocation_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_HNBAP_GeographicalLocation;

#ifdef __cplusplus
}
#endif

#endif	/* _HNBAP_GeographicalLocation_H_ */
#include <asn_internal.h>
