/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "HNBAP-IEs"
 * 	found in "../../asn1/hnbap/HNBAP-IEs.asn"
 * 	`asn1c -R -fcompound-names`
 */

#ifndef	_HNBAP_ConfigurationInformation_H_
#define	_HNBAP_ConfigurationInformation_H_


#include <asn_application.h>

/* Including external dependencies */
#include <osmocom/hnbap/HNBAP_HNBConfigurationInformationProvided.h>
#include <osmocom/hnbap/HNBAP_HNBConfigurationInformationMissing.h>
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum HNBAP_ConfigurationInformation_PR {
	HNBAP_ConfigurationInformation_PR_NOTHING,	/* No components present */
	HNBAP_ConfigurationInformation_PR_provided,
	HNBAP_ConfigurationInformation_PR_missing,
	/* Extensions may appear below */
	
} HNBAP_ConfigurationInformation_PR;

/* HNBAP_ConfigurationInformation */
typedef struct HNBAP_ConfigurationInformation {
	HNBAP_ConfigurationInformation_PR present;
	union HNBAP_ConfigurationInformation_u {
		HNBAP_HNBConfigurationInformationProvided_t	 provided;
		HNBAP_HNBConfigurationInformationMissing_t	 missing;
		/*
		 * This type is extensible,
		 * possible extensions are below.
		 */
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} HNBAP_ConfigurationInformation_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_HNBAP_ConfigurationInformation;

#ifdef __cplusplus
}
#endif

#endif	/* _HNBAP_ConfigurationInformation_H_ */
#include <asn_internal.h>
