/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "HNBAP-CommonDataTypes"
 * 	found in "../../asn1/hnbap/HNBAP-CommonDataTypes.asn"
 * 	`asn1c -R`
 */

#ifndef	_HNBAP_PrivateIE_ID_H_
#define	_HNBAP_PrivateIE_ID_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>
#include <OBJECT_IDENTIFIER.h>
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum HNBAP_PrivateIE_ID_PR {
	HNBAP_PrivateIE_ID_PR_NOTHING,	/* No components present */
	HNBAP_PrivateIE_ID_PR_local,
	HNBAP_PrivateIE_ID_PR_global
} HNBAP_PrivateIE_ID_PR;

/* HNBAP_PrivateIE-ID */
typedef struct HNBAP_PrivateIE_ID {
	HNBAP_PrivateIE_ID_PR present;
	union HNBAP_PrivateIE_ID_u {
		long	 local;
		OBJECT_IDENTIFIER_t	 global;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} HNBAP_PrivateIE_ID_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_HNBAP_PrivateIE_ID;

#ifdef __cplusplus
}
#endif

#endif	/* _HNBAP_PrivateIE_ID_H_ */
#include <asn_internal.h>
