/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "HNBAP-CommonDataTypes"
 * 	found in "../../asn1/hnbap/HNBAP-CommonDataTypes.asn"
 * 	`asn1c -R -fcompound-names`
 */

#ifndef	_HNBAP_Presence_H_
#define	_HNBAP_Presence_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum HNBAP_Presence {
	HNBAP_Presence_optional	= 0,
	HNBAP_Presence_conditional	= 1,
	HNBAP_Presence_mandatory	= 2
} e_HNBAP_Presence;

/* HNBAP_Presence */
typedef long	 HNBAP_Presence_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_HNBAP_Presence;
asn_struct_free_f HNBAP_Presence_free;
asn_struct_print_f HNBAP_Presence_print;
asn_constr_check_f HNBAP_Presence_constraint;
ber_type_decoder_f HNBAP_Presence_decode_ber;
der_type_encoder_f HNBAP_Presence_encode_der;
xer_type_decoder_f HNBAP_Presence_decode_xer;
xer_type_encoder_f HNBAP_Presence_encode_xer;
per_type_decoder_f HNBAP_Presence_decode_uper;
per_type_encoder_f HNBAP_Presence_encode_uper;
per_type_decoder_f HNBAP_Presence_decode_aper;
per_type_encoder_f HNBAP_Presence_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _HNBAP_Presence_H_ */
#include <asn_internal.h>
