/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "HNBAP-IEs"
 * 	found in "../../asn1/hnbap/HNBAP-IEs.asn"
 * 	`asn1c -R -gen-PER`
 */

#ifndef	_HNBAP_UE_Identity_H_
#define	_HNBAP_UE_Identity_H_


#include <asn_application.h>

/* Including external dependencies */
#include <osmocom/hnbap/HNBAP_IMSI.h>
#include <osmocom/hnbap/HNBAP_TMSILAI.h>
#include <osmocom/hnbap/HNBAP_PTMSIRAI.h>
#include <osmocom/hnbap/HNBAP_IMEI.h>
#include <osmocom/hnbap/HNBAP_ESN.h>
#include <osmocom/hnbap/HNBAP_IMSIDS41.h>
#include <osmocom/hnbap/HNBAP_IMSIESN.h>
#include <osmocom/hnbap/HNBAP_TMSIDS41.h>
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum HNBAP_UE_Identity_PR {
	HNBAP_UE_Identity_PR_NOTHING,	/* No components present */
	HNBAP_UE_Identity_PR_iMSI,
	HNBAP_UE_Identity_PR_tMSILAI,
	HNBAP_UE_Identity_PR_pTMSIRAI,
	HNBAP_UE_Identity_PR_iMEI,
	HNBAP_UE_Identity_PR_eSN,
	HNBAP_UE_Identity_PR_iMSIDS41,
	HNBAP_UE_Identity_PR_iMSIESN,
	HNBAP_UE_Identity_PR_tMSIDS41,
	/* Extensions may appear below */
	
} HNBAP_UE_Identity_PR;

/* HNBAP_UE-Identity */
typedef struct HNBAP_UE_Identity {
	HNBAP_UE_Identity_PR present;
	union HNBAP_UE_Identity_u {
		HNBAP_IMSI_t	 iMSI;
		HNBAP_TMSILAI_t	 tMSILAI;
		HNBAP_PTMSIRAI_t	 pTMSIRAI;
		HNBAP_IMEI_t	 iMEI;
		HNBAP_ESN_t	 eSN;
		HNBAP_IMSIDS41_t	 iMSIDS41;
		HNBAP_IMSIESN_t	 iMSIESN;
		HNBAP_TMSIDS41_t	 tMSIDS41;
		/*
		 * This type is extensible,
		 * possible extensions are below.
		 */
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} HNBAP_UE_Identity_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_HNBAP_UE_Identity;

#ifdef __cplusplus
}
#endif

#endif	/* _HNBAP_UE_Identity_H_ */
#include <asn_internal.h>
