/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "HNBAP-IEs"
 * 	found in "../../asn1/hnbap/HNBAP-IEs.asn"
 * 	`asn1c -R -gen-PER`
 */

#ifndef	_HNBAP_LAI_H_
#define	_HNBAP_LAI_H_


#include <asn_application.h>

/* Including external dependencies */
#include <osmocom/hnbap/HNBAP_PLMNidentity.h>
#include <osmocom/hnbap/HNBAP_LAC.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* HNBAP_LAI */
typedef struct HNBAP_LAI {
	HNBAP_PLMNidentity_t	 pLMNID;
	HNBAP_LAC_t	 lAC;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} HNBAP_LAI_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_HNBAP_LAI;

#ifdef __cplusplus
}
#endif

#endif	/* _HNBAP_LAI_H_ */
#include <asn_internal.h>
