/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "HNBAP-IEs"
 * 	found in "../../asn1/hnbap/HNBAP-IEs.asn"
 * 	`asn1c -R -fcompound-names`
 */

#ifndef	_HNBAP_CN_DomainIndicator_H_
#define	_HNBAP_CN_DomainIndicator_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum HNBAP_CN_DomainIndicator {
	HNBAP_CN_DomainIndicator_cs_domain	= 0,
	HNBAP_CN_DomainIndicator_ps_domain	= 1
} e_HNBAP_CN_DomainIndicator;

/* HNBAP_CN-DomainIndicator */
typedef long	 HNBAP_CN_DomainIndicator_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_HNBAP_CN_DomainIndicator;
asn_struct_free_f HNBAP_CN_DomainIndicator_free;
asn_struct_print_f HNBAP_CN_DomainIndicator_print;
asn_constr_check_f HNBAP_CN_DomainIndicator_constraint;
ber_type_decoder_f HNBAP_CN_DomainIndicator_decode_ber;
der_type_encoder_f HNBAP_CN_DomainIndicator_encode_der;
xer_type_decoder_f HNBAP_CN_DomainIndicator_decode_xer;
xer_type_encoder_f HNBAP_CN_DomainIndicator_encode_xer;
per_type_decoder_f HNBAP_CN_DomainIndicator_decode_uper;
per_type_encoder_f HNBAP_CN_DomainIndicator_encode_uper;
per_type_decoder_f HNBAP_CN_DomainIndicator_decode_aper;
per_type_encoder_f HNBAP_CN_DomainIndicator_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _HNBAP_CN_DomainIndicator_H_ */
#include <asn_internal.h>
