/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "HNBAP-PDU"
 * 	found in "../../asn1/hnbap/HNBAP-PDU.asn"
 * 	`asn1c -R -gen-PER`
 */

#ifndef	_HNBAP_InitiatingMessage_H_
#define	_HNBAP_InitiatingMessage_H_


#include <asn_application.h>

/* Including external dependencies */
#include <osmocom/hnbap/HNBAP_ProcedureCode.h>
#include <osmocom/hnbap/HNBAP_Criticality.h>
#include <ANY.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* HNBAP_InitiatingMessage */
typedef struct HNBAP_InitiatingMessage {
	HNBAP_ProcedureCode_t	 procedureCode;
	HNBAP_Criticality_t	 criticality;
	ANY_t	 value;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} HNBAP_InitiatingMessage_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_HNBAP_InitiatingMessage;

#ifdef __cplusplus
}
#endif

#endif	/* _HNBAP_InitiatingMessage_H_ */
#include <asn_internal.h>
