/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "HNBAP-IEs"
 * 	found in "../../asn1/hnbap/HNBAP-IEs.asn"
 * 	`asn1c -R`
 */

#ifndef	_HNBAP_HNB_GWResponse_H_
#define	_HNBAP_HNB_GWResponse_H_


#include <asn_application.h>

/* Including external dependencies */
#include <osmocom/hnbap/HNBAP_HNBConfigInfo.h>
#include <osmocom/hnbap/HNBAP_RNC-ID.h>
#include <osmocom/hnbap/HNBAP_UnknownU-RNTIIndication.h>
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum HNBAP_HNB_GWResponse_PR {
	HNBAP_HNB_GWResponse_PR_NOTHING,	/* No components present */
	HNBAP_HNB_GWResponse_PR_hNB,
	HNBAP_HNB_GWResponse_PR_macroRNC,
	HNBAP_HNB_GWResponse_PR_unknownU_RNTIIndication,
	/* Extensions may appear below */
	
} HNBAP_HNB_GWResponse_PR;

/* HNBAP_HNB-GWResponse */
typedef struct HNBAP_HNB_GWResponse {
	HNBAP_HNB_GWResponse_PR present;
	union HNBAP_HNB_GWResponse_u {
		HNBAP_HNBConfigInfo_t	 hNB;
		HNBAP_RNC_ID_t	 macroRNC;
		HNBAP_UnknownU_RNTIIndication_t	 unknownU_RNTIIndication;
		/*
		 * This type is extensible,
		 * possible extensions are below.
		 */
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} HNBAP_HNB_GWResponse_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_HNBAP_HNB_GWResponse;

#ifdef __cplusplus
}
#endif

#endif	/* _HNBAP_HNB_GWResponse_H_ */
#include <asn_internal.h>
