/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "HNBAP-IEs"
 * 	found in "../../asn1/hnbap/HNBAP-IEs.asn"
 * 	`asn1c -R -fcompound-names`
 */

#ifndef	_HNBAP_TMSILAI_H_
#define	_HNBAP_TMSILAI_H_


#include <asn_application.h>

/* Including external dependencies */
#include <BIT_STRING.h>
#include <osmocom/hnbap/HNBAP_LAI.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* HNBAP_TMSILAI */
typedef struct HNBAP_TMSILAI {
	BIT_STRING_t	 tMSI;
	HNBAP_LAI_t	 lAI;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} HNBAP_TMSILAI_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_HNBAP_TMSILAI;

#ifdef __cplusplus
}
#endif

#endif	/* _HNBAP_TMSILAI_H_ */
#include <asn_internal.h>
