/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "HNBAP-IEs"
 * 	found in "../../asn1/hnbap/HNBAP-IEs.asn"
 * 	`asn1c -R -gen-PER`
 */

#ifndef	_HNBAP_UnknownU_RNTIIndication_H_
#define	_HNBAP_UnknownU_RNTIIndication_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum HNBAP_UnknownU_RNTIIndication {
	HNBAP_UnknownU_RNTIIndication_unknown	= 0
	/*
	 * Enumeration is extensible
	 */
} e_HNBAP_UnknownU_RNTIIndication;

/* HNBAP_UnknownU-RNTIIndication */
typedef long	 HNBAP_UnknownU_RNTIIndication_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_HNBAP_UnknownU_RNTIIndication;
asn_struct_free_f HNBAP_UnknownU_RNTIIndication_free;
asn_struct_print_f HNBAP_UnknownU_RNTIIndication_print;
asn_constr_check_f HNBAP_UnknownU_RNTIIndication_constraint;
ber_type_decoder_f HNBAP_UnknownU_RNTIIndication_decode_ber;
der_type_encoder_f HNBAP_UnknownU_RNTIIndication_encode_der;
xer_type_decoder_f HNBAP_UnknownU_RNTIIndication_decode_xer;
xer_type_encoder_f HNBAP_UnknownU_RNTIIndication_encode_xer;
per_type_decoder_f HNBAP_UnknownU_RNTIIndication_decode_uper;
per_type_encoder_f HNBAP_UnknownU_RNTIIndication_encode_uper;
per_type_decoder_f HNBAP_UnknownU_RNTIIndication_decode_aper;
per_type_encoder_f HNBAP_UnknownU_RNTIIndication_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _HNBAP_UnknownU_RNTIIndication_H_ */
#include <asn_internal.h>
