/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "HNBAP-CommonDataTypes"
 * 	found in "../../asn1/hnbap/HNBAP-CommonDataTypes.asn"
 * 	`asn1c -R -fcompound-names`
 */

#ifndef	_HNBAP_ProcedureCode_H_
#define	_HNBAP_ProcedureCode_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum HNBAP_ProcedureCode {
	HNBAP_ProcedureCode_id_HNBRegister	= 1,
	HNBAP_ProcedureCode_id_HNBDe_Register	= 2,
	HNBAP_ProcedureCode_id_UERegister	= 3,
	HNBAP_ProcedureCode_id_UEDe_Register	= 4,
	HNBAP_ProcedureCode_id_ErrorIndication	= 5,
	HNBAP_ProcedureCode_id_privateMessage	= 6,
	HNBAP_ProcedureCode_id_CSGMembershipUpdate	= 7,
	HNBAP_ProcedureCode_id_TNLUpdate	= 9,
	HNBAP_ProcedureCode_id_HNBConfigTransfer	= 10,
	HNBAP_ProcedureCode_id_RelocationComplete	= 11,
	HNBAP_ProcedureCode_id_U_RNTIQuery	= 14
} e_HNBAP_ProcedureCode;

/* HNBAP_ProcedureCode */
typedef long	 HNBAP_ProcedureCode_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_HNBAP_ProcedureCode;
asn_struct_free_f HNBAP_ProcedureCode_free;
asn_struct_print_f HNBAP_ProcedureCode_print;
asn_constr_check_f HNBAP_ProcedureCode_constraint;
ber_type_decoder_f HNBAP_ProcedureCode_decode_ber;
der_type_encoder_f HNBAP_ProcedureCode_encode_der;
xer_type_decoder_f HNBAP_ProcedureCode_decode_xer;
xer_type_encoder_f HNBAP_ProcedureCode_encode_xer;
per_type_decoder_f HNBAP_ProcedureCode_decode_uper;
per_type_encoder_f HNBAP_ProcedureCode_encode_uper;
per_type_decoder_f HNBAP_ProcedureCode_decode_aper;
per_type_encoder_f HNBAP_ProcedureCode_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _HNBAP_ProcedureCode_H_ */
#include <asn_internal.h>
