/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "HNBAP-IEs"
 * 	found in "../../asn1/hnbap/HNBAP-IEs.asn"
 * 	`asn1c -R -gen-PER`
 */

#ifndef	_HNBAP_HNBConfigurationInformationProvided_H_
#define	_HNBAP_HNBConfigurationInformationProvided_H_


#include <asn_application.h>

/* Including external dependencies */
#include <osmocom/hnbap/HNBAP_PSC.h>
#include <osmocom/hnbap/HNBAP_CSG-ID.h>
#include <osmocom/hnbap/HNBAP_HNB-Cell-Access-Mode.h>
#include <osmocom/hnbap/HNBAP_Iurh-Signalling-TNL-AddressList.h>
#include <osmocom/hnbap/HNBAP_IE-Extensions.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* HNBAP_HNBConfigurationInformationProvided */
typedef struct HNBAP_HNBConfigurationInformationProvided {
	HNBAP_PSC_t	*psc	/* OPTIONAL */;
	HNBAP_CSG_ID_t	*cSG_ID	/* OPTIONAL */;
	HNBAP_HNB_Cell_Access_Mode_t	 hNB_Cell_Access_Mode;
	HNBAP_Iurh_Signalling_TNL_AddressList_t	 iurh_Signalling_TNL_AddressList;
	HNBAP_IE_Extensions_t	*iE_Extensions	/* OPTIONAL */;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} HNBAP_HNBConfigurationInformationProvided_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_HNBAP_HNBConfigurationInformationProvided;

#ifdef __cplusplus
}
#endif

#endif	/* _HNBAP_HNBConfigurationInformationProvided_H_ */
#include <asn_internal.h>
