/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "HNBAP-PDU"
 * 	found in "../../asn1/hnbap/HNBAP-PDU.asn"
 * 	`asn1c -R -gen-PER`
 */

#ifndef	_HNBAP_IE_H_
#define	_HNBAP_IE_H_


#include <asn_application.h>

/* Including external dependencies */
#include <osmocom/hnbap/HNBAP_ProtocolIE-ID.h>
#include <osmocom/hnbap/HNBAP_Criticality.h>
#include <ANY.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* HNBAP_IE */
typedef struct HNBAP_IE {
	HNBAP_ProtocolIE_ID_t	 id;
	HNBAP_Criticality_t	 criticality;
	ANY_t	 value;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} HNBAP_IE_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_HNBAP_IE;

#ifdef __cplusplus
}
#endif

#endif	/* _HNBAP_IE_H_ */
#include <asn_internal.h>
