/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "HNBAP-CommonDataTypes"
 * 	found in "../../asn1/hnbap/HNBAP-CommonDataTypes.asn"
 * 	`asn1c -R -fcompound-names`
 */

#ifndef	_HNBAP_Criticality_H_
#define	_HNBAP_Criticality_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum HNBAP_Criticality {
	HNBAP_Criticality_reject	= 0,
	HNBAP_Criticality_ignore	= 1,
	HNBAP_Criticality_notify	= 2
} e_HNBAP_Criticality;

/* HNBAP_Criticality */
typedef long	 HNBAP_Criticality_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_HNBAP_Criticality;
asn_struct_free_f HNBAP_Criticality_free;
asn_struct_print_f HNBAP_Criticality_print;
asn_constr_check_f HNBAP_Criticality_constraint;
ber_type_decoder_f HNBAP_Criticality_decode_ber;
der_type_encoder_f HNBAP_Criticality_encode_der;
xer_type_decoder_f HNBAP_Criticality_decode_xer;
xer_type_encoder_f HNBAP_Criticality_encode_xer;
per_type_decoder_f HNBAP_Criticality_decode_uper;
per_type_encoder_f HNBAP_Criticality_encode_uper;
per_type_decoder_f HNBAP_Criticality_decode_aper;
per_type_encoder_f HNBAP_Criticality_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _HNBAP_Criticality_H_ */
#include <asn_internal.h>
