/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "HNBAP-IEs"
 * 	found in "../../asn1/hnbap/HNBAP-IEs.asn"
 * 	`asn1c -R -gen-PER`
 */

#ifndef	_HNBAP_URAIdentityList_H_
#define	_HNBAP_URAIdentityList_H_


#include <asn_application.h>

/* Including external dependencies */
#include <osmocom/hnbap/HNBAP_URAIdentity.h>
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>

#ifdef __cplusplus
extern "C" {
#endif

/* HNBAP_URAIdentityList */
typedef struct HNBAP_URAIdentityList {
	A_SEQUENCE_OF(HNBAP_URAIdentity_t) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} HNBAP_URAIdentityList_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_HNBAP_URAIdentityList;

#ifdef __cplusplus
}
#endif

#endif	/* _HNBAP_URAIdentityList_H_ */
#include <asn_internal.h>
