/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "HNBAP-IEs"
 * 	found in "../../asn1/hnbap/HNBAP-IEs.asn"
 * 	`asn1c -R -fcompound-names`
 */

#ifndef	_HNBAP_PTMSIRAI_H_
#define	_HNBAP_PTMSIRAI_H_


#include <asn_application.h>

/* Including external dependencies */
#include <osmocom/hnbap/HNBAP_PTMSI.h>
#include <osmocom/hnbap/HNBAP_RAI.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* HNBAP_PTMSIRAI */
typedef struct HNBAP_PTMSIRAI {
	HNBAP_PTMSI_t	 pTMSI;
	HNBAP_RAI_t	 rAI;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} HNBAP_PTMSIRAI_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_HNBAP_PTMSIRAI;

#ifdef __cplusplus
}
#endif

#endif	/* _HNBAP_PTMSIRAI_H_ */
#include <asn_internal.h>
