/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "HNBAP-IEs"
 * 	found in "../../asn1/hnbap/HNBAP-IEs.asn"
 * 	`asn1c -R -gen-PER`
 */

#ifndef	_HNBAP_Tunnel_Information_H_
#define	_HNBAP_Tunnel_Information_H_


#include <asn_application.h>

/* Including external dependencies */
#include <osmocom/hnbap/HNBAP_IP-Address.h>
#include <osmocom/hnbap/HNBAP_UDP-Port-Number.h>
#include <osmocom/hnbap/HNBAP_IE-Extensions.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* HNBAP_Tunnel-Information */
typedef struct HNBAP_Tunnel_Information {
	HNBAP_IP_Address_t	 iP_Address;
	HNBAP_UDP_Port_Number_t	*uDP_Port_Number	/* OPTIONAL */;
	HNBAP_IE_Extensions_t	*iE_Extensions	/* OPTIONAL */;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} HNBAP_Tunnel_Information_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_HNBAP_Tunnel_Information;

#ifdef __cplusplus
}
#endif

#endif	/* _HNBAP_Tunnel_Information_H_ */
#include <asn_internal.h>
