/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "HNBAP-IEs"
 * 	found in "../../asn1/hnbap/HNBAP-IEs.asn"
 * 	`asn1c -R -fcompound-names`
 */

#ifndef	_HNBAP_MacroCellID_H_
#define	_HNBAP_MacroCellID_H_


#include <asn_application.h>

/* Including external dependencies */
#include <osmocom/hnbap/HNBAP_UTRANCellID.h>
#include <osmocom/hnbap/HNBAP_CGI.h>
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum HNBAP_MacroCellID_PR {
	HNBAP_MacroCellID_PR_NOTHING,	/* No components present */
	HNBAP_MacroCellID_PR_uTRANCellID,
	HNBAP_MacroCellID_PR_gERANCellID,
	/* Extensions may appear below */
	
} HNBAP_MacroCellID_PR;

/* HNBAP_MacroCellID */
typedef struct HNBAP_MacroCellID {
	HNBAP_MacroCellID_PR present;
	union HNBAP_MacroCellID_u {
		HNBAP_UTRANCellID_t	 uTRANCellID;
		HNBAP_CGI_t	 gERANCellID;
		/*
		 * This type is extensible,
		 * possible extensions are below.
		 */
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} HNBAP_MacroCellID_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_HNBAP_MacroCellID;

#ifdef __cplusplus
}
#endif

#endif	/* _HNBAP_MacroCellID_H_ */
#include <asn_internal.h>
