/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "HNBAP-IEs"
 * 	found in "../../asn1/hnbap/HNBAP-IEs.asn"
 * 	`asn1c -R -gen-PER`
 */

#ifndef	_HNBAP_NeighbourIdentity_H_
#define	_HNBAP_NeighbourIdentity_H_


#include <asn_application.h>

/* Including external dependencies */
#include <osmocom/hnbap/HNBAP_HNB-RNL-Identity.h>
#include <osmocom/hnbap/HNBAP_CellIdentity.h>
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum HNBAP_NeighbourIdentity_PR {
	HNBAP_NeighbourIdentity_PR_NOTHING,	/* No components present */
	HNBAP_NeighbourIdentity_PR_hNB_RNL_Identity,
	HNBAP_NeighbourIdentity_PR_cell_ID,
	/* Extensions may appear below */
	
} HNBAP_NeighbourIdentity_PR;

/* HNBAP_NeighbourIdentity */
typedef struct HNBAP_NeighbourIdentity {
	HNBAP_NeighbourIdentity_PR present;
	union HNBAP_NeighbourIdentity_u {
		HNBAP_HNB_RNL_Identity_t	 hNB_RNL_Identity;
		HNBAP_CellIdentity_t	 cell_ID;
		/*
		 * This type is extensible,
		 * possible extensions are below.
		 */
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} HNBAP_NeighbourIdentity_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_HNBAP_NeighbourIdentity;

#ifdef __cplusplus
}
#endif

#endif	/* _HNBAP_NeighbourIdentity_H_ */
#include <asn_internal.h>
