/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "HNBAP-IEs"
 * 	found in "../../asn1/hnbap/HNBAP-IEs.asn"
 * 	`asn1c -R -gen-PER`
 */

#ifndef	_HNBAP_CauseMisc_H_
#define	_HNBAP_CauseMisc_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum HNBAP_CauseMisc {
	HNBAP_CauseMisc_processing_overload	= 0,
	HNBAP_CauseMisc_hardware_failure	= 1,
	HNBAP_CauseMisc_o_and_m_intervention	= 2,
	HNBAP_CauseMisc_unspecified	= 3
	/*
	 * Enumeration is extensible
	 */
} e_HNBAP_CauseMisc;

/* HNBAP_CauseMisc */
typedef long	 HNBAP_CauseMisc_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_HNBAP_CauseMisc;
asn_struct_free_f HNBAP_CauseMisc_free;
asn_struct_print_f HNBAP_CauseMisc_print;
asn_constr_check_f HNBAP_CauseMisc_constraint;
ber_type_decoder_f HNBAP_CauseMisc_decode_ber;
der_type_encoder_f HNBAP_CauseMisc_encode_der;
xer_type_decoder_f HNBAP_CauseMisc_decode_xer;
xer_type_encoder_f HNBAP_CauseMisc_encode_xer;
per_type_decoder_f HNBAP_CauseMisc_decode_uper;
per_type_encoder_f HNBAP_CauseMisc_encode_uper;
per_type_decoder_f HNBAP_CauseMisc_decode_aper;
per_type_encoder_f HNBAP_CauseMisc_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _HNBAP_CauseMisc_H_ */
#include <asn_internal.h>
