/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "HNBAP-CommonDataTypes"
 * 	found in "../../asn1/hnbap/HNBAP-CommonDataTypes.asn"
 * 	`asn1c -R -fcompound-names`
 */

#ifndef	_HNBAP_ProtocolIE_ID_H_
#define	_HNBAP_ProtocolIE_ID_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum HNBAP_ProtocolIE_ID {
	HNBAP_ProtocolIE_ID_id_Cause	= 1,
	HNBAP_ProtocolIE_ID_id_CriticalityDiagnostics	= 2,
	HNBAP_ProtocolIE_ID_id_HNB_Identity	= 3,
	HNBAP_ProtocolIE_ID_id_Context_ID	= 4,
	HNBAP_ProtocolIE_ID_id_UE_Identity	= 5,
	HNBAP_ProtocolIE_ID_id_LAC	= 6,
	HNBAP_ProtocolIE_ID_id_RAC	= 7,
	HNBAP_ProtocolIE_ID_id_HNB_Location_Information	= 8,
	HNBAP_ProtocolIE_ID_id_PLMNidentity	= 9,
	HNBAP_ProtocolIE_ID_id_SAC	= 10,
	HNBAP_ProtocolIE_ID_id_CellIdentity	= 11,
	HNBAP_ProtocolIE_ID_id_Registration_Cause	= 12,
	HNBAP_ProtocolIE_ID_id_UE_Capabilities	= 13,
	HNBAP_ProtocolIE_ID_id_RNC_ID	= 14,
	HNBAP_ProtocolIE_ID_id_CSG_ID	= 15,
	HNBAP_ProtocolIE_ID_id_BackoffTimer	= 16,
	HNBAP_ProtocolIE_ID_id_HNB_Internet_Information	= 17,
	HNBAP_ProtocolIE_ID_id_HNB_Cell_Access_Mode	= 18,
	HNBAP_ProtocolIE_ID_id_MuxPortNumber	= 19,
	HNBAP_ProtocolIE_ID_id_Service_Area_For_Broadcast	= 20,
	HNBAP_ProtocolIE_ID_id_CSGMembershipStatus	= 21,
	HNBAP_ProtocolIE_ID_id_RABList	= 22,
	HNBAP_ProtocolIE_ID_id_HNBConfigInfo	= 23,
	HNBAP_ProtocolIE_ID_id_AccessResult	= 25,
	HNBAP_ProtocolIE_ID_id_Update_cause	= 26,
	HNBAP_ProtocolIE_ID_id_NeighbourInfoList	= 27,
	HNBAP_ProtocolIE_ID_id_NeighbourInfoRequestList	= 28,
	HNBAP_ProtocolIE_ID_id_Iurh_Signalling_TNL_Address	= 29,
	HNBAP_ProtocolIE_ID_id_PSC	= 30,
	HNBAP_ProtocolIE_ID_id_HNB_Cell_Identifier	= 31,
	HNBAP_ProtocolIE_ID_id_Tunnel_Information	= 41,
	HNBAP_ProtocolIE_ID_id_CELL_FACHMobilitySupport	= 42,
	HNBAP_ProtocolIE_ID_id_S_RNTIPrefix	= 43,
	HNBAP_ProtocolIE_ID_id_URAIdentity	= 44,
	HNBAP_ProtocolIE_ID_id_NeighbourIdentity	= 45,
	HNBAP_ProtocolIE_ID_id_HNBCapacity	= 46,
	HNBAP_ProtocolIE_ID_id_NeighbourCellIdentityList	= 47,
	HNBAP_ProtocolIE_ID_id_AdditionalNeighbourInfoList	= 48,
	HNBAP_ProtocolIE_ID_id_U_RNTI	= 49,
	HNBAP_ProtocolIE_ID_id_UnknownU_RNTIIndication	= 50,
	HNBAP_ProtocolIE_ID_id_HNB_GWResponse	= 51,
	HNBAP_ProtocolIE_ID_id_URAIdentityList	= 52
} e_HNBAP_ProtocolIE_ID;

/* HNBAP_ProtocolIE-ID */
typedef long	 HNBAP_ProtocolIE_ID_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_HNBAP_ProtocolIE_ID;
asn_struct_free_f HNBAP_ProtocolIE_ID_free;
asn_struct_print_f HNBAP_ProtocolIE_ID_print;
asn_constr_check_f HNBAP_ProtocolIE_ID_constraint;
ber_type_decoder_f HNBAP_ProtocolIE_ID_decode_ber;
der_type_encoder_f HNBAP_ProtocolIE_ID_encode_der;
xer_type_decoder_f HNBAP_ProtocolIE_ID_decode_xer;
xer_type_encoder_f HNBAP_ProtocolIE_ID_encode_xer;
per_type_decoder_f HNBAP_ProtocolIE_ID_decode_uper;
per_type_encoder_f HNBAP_ProtocolIE_ID_encode_uper;
per_type_decoder_f HNBAP_ProtocolIE_ID_decode_aper;
per_type_encoder_f HNBAP_ProtocolIE_ID_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _HNBAP_ProtocolIE_ID_H_ */
#include <asn_internal.h>
