/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "HNBAP-IEs"
 * 	found in "../../asn1/hnbap/HNBAP-IEs.asn"
 * 	`asn1c -R -fcompound-names`
 */

#ifndef	_HNBAP_CauseTransport_H_
#define	_HNBAP_CauseTransport_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum HNBAP_CauseTransport {
	HNBAP_CauseTransport_transport_resource_unavailable	= 0,
	HNBAP_CauseTransport_unspecified	= 1
	/*
	 * Enumeration is extensible
	 */
} e_HNBAP_CauseTransport;

/* HNBAP_CauseTransport */
typedef long	 HNBAP_CauseTransport_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_HNBAP_CauseTransport;
asn_struct_free_f HNBAP_CauseTransport_free;
asn_struct_print_f HNBAP_CauseTransport_print;
asn_constr_check_f HNBAP_CauseTransport_constraint;
ber_type_decoder_f HNBAP_CauseTransport_decode_ber;
der_type_encoder_f HNBAP_CauseTransport_encode_der;
xer_type_decoder_f HNBAP_CauseTransport_decode_xer;
xer_type_encoder_f HNBAP_CauseTransport_encode_xer;
per_type_decoder_f HNBAP_CauseTransport_decode_uper;
per_type_encoder_f HNBAP_CauseTransport_encode_uper;
per_type_decoder_f HNBAP_CauseTransport_decode_aper;
per_type_encoder_f HNBAP_CauseTransport_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _HNBAP_CauseTransport_H_ */
#include <asn_internal.h>
