/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "HNBAP-IEs"
 * 	found in "../../asn1/hnbap/HNBAP-IEs.asn"
 * 	`asn1c -R -fcompound-names`
 */

#ifndef	_HNBAP_RAI_H_
#define	_HNBAP_RAI_H_


#include <asn_application.h>

/* Including external dependencies */
#include <osmocom/hnbap/HNBAP_LAI.h>
#include <osmocom/hnbap/HNBAP_RAC.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* HNBAP_RAI */
typedef struct HNBAP_RAI {
	HNBAP_LAI_t	 lAI;
	HNBAP_RAC_t	 rAC;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} HNBAP_RAI_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_HNBAP_RAI;

#ifdef __cplusplus
}
#endif

#endif	/* _HNBAP_RAI_H_ */
#include <asn_internal.h>
