/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "HNBAP-IEs"
 * 	found in "../../asn1/hnbap/HNBAP-IEs.asn"
 * 	`asn1c -R -gen-PER`
 */

#ifndef	_HNBAP_MuxPortNumber_H_
#define	_HNBAP_MuxPortNumber_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* HNBAP_MuxPortNumber */
typedef long	 HNBAP_MuxPortNumber_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_HNBAP_MuxPortNumber;
asn_struct_free_f HNBAP_MuxPortNumber_free;
asn_struct_print_f HNBAP_MuxPortNumber_print;
asn_constr_check_f HNBAP_MuxPortNumber_constraint;
ber_type_decoder_f HNBAP_MuxPortNumber_decode_ber;
der_type_encoder_f HNBAP_MuxPortNumber_encode_der;
xer_type_decoder_f HNBAP_MuxPortNumber_decode_xer;
xer_type_encoder_f HNBAP_MuxPortNumber_encode_xer;
per_type_decoder_f HNBAP_MuxPortNumber_decode_uper;
per_type_encoder_f HNBAP_MuxPortNumber_encode_uper;
per_type_decoder_f HNBAP_MuxPortNumber_decode_aper;
per_type_encoder_f HNBAP_MuxPortNumber_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _HNBAP_MuxPortNumber_H_ */
#include <asn_internal.h>
