/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "HNBAP-IEs"
 * 	found in "../../asn1/hnbap/HNBAP-IEs.asn"
 * 	`asn1c -R`
 */

#ifndef	_HNBAP_CauseProtocol_H_
#define	_HNBAP_CauseProtocol_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum HNBAP_CauseProtocol {
	HNBAP_CauseProtocol_transfer_syntax_error	= 0,
	HNBAP_CauseProtocol_abstract_syntax_error_reject	= 1,
	HNBAP_CauseProtocol_abstract_syntax_error_ignore_and_notify	= 2,
	HNBAP_CauseProtocol_message_not_compatible_with_receiver_state	= 3,
	HNBAP_CauseProtocol_semantic_error	= 4,
	HNBAP_CauseProtocol_unspecified	= 5,
	HNBAP_CauseProtocol_abstract_syntax_error_falsely_constructed_message	= 6
	/*
	 * Enumeration is extensible
	 */
} e_HNBAP_CauseProtocol;

/* HNBAP_CauseProtocol */
typedef long	 HNBAP_CauseProtocol_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_HNBAP_CauseProtocol;
asn_struct_free_f HNBAP_CauseProtocol_free;
asn_struct_print_f HNBAP_CauseProtocol_print;
asn_constr_check_f HNBAP_CauseProtocol_constraint;
ber_type_decoder_f HNBAP_CauseProtocol_decode_ber;
der_type_encoder_f HNBAP_CauseProtocol_encode_der;
xer_type_decoder_f HNBAP_CauseProtocol_decode_xer;
xer_type_encoder_f HNBAP_CauseProtocol_encode_xer;
per_type_decoder_f HNBAP_CauseProtocol_decode_uper;
per_type_encoder_f HNBAP_CauseProtocol_encode_uper;
per_type_decoder_f HNBAP_CauseProtocol_decode_aper;
per_type_encoder_f HNBAP_CauseProtocol_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _HNBAP_CauseProtocol_H_ */
#include <asn_internal.h>
