/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "HNBAP-PDU"
 * 	found in "../../asn1/hnbap/HNBAP-PDU.asn"
 * 	`asn1c -R -fcompound-names`
 */

#ifndef	_HNBAP_CSGMembershipUpdate_H_
#define	_HNBAP_CSGMembershipUpdate_H_


#include <asn_application.h>

/* Including external dependencies */
#include <osmocom/hnbap/HNBAP_IE.h>
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* HNBAP_CSGMembershipUpdate */
typedef struct HNBAP_CSGMembershipUpdate {
	struct HNBAP_CSGMembershipUpdate__csgMembershipUpdate_ies {
		A_SEQUENCE_OF(HNBAP_IE_t) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} csgMembershipUpdate_ies;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} HNBAP_CSGMembershipUpdate_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_HNBAP_CSGMembershipUpdate;

#ifdef __cplusplus
}
#endif

#endif	/* _HNBAP_CSGMembershipUpdate_H_ */
#include <asn_internal.h>
