/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "SABP-IEs"
 * 	found in "../../asn1/sabp/SABP-IEs.asn"
 * 	`asn1c -R -fcompound-names`
 */

#ifndef	_SABP_MessageStructure_H_
#define	_SABP_MessageStructure_H_


#include <asn_application.h>

/* Including external dependencies */
#include <osmocom/sabp/SABP_MessageStructure-Value.h>
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>

#ifdef __cplusplus
extern "C" {
#endif

/* SABP_MessageStructure */
typedef struct SABP_MessageStructure {
	A_SEQUENCE_OF(SABP_MessageStructure_Value_t) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SABP_MessageStructure_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SABP_MessageStructure;

#ifdef __cplusplus
}
#endif

#endif	/* _SABP_MessageStructure_H_ */
#include <asn_internal.h>
