/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "SABP-CommonDataTypes"
 * 	found in "../../asn1/sabp/SABP-CommonDataTypes.asn"
 */

#ifndef	_SABP_Criticality_H_
#define	_SABP_Criticality_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum SABP_Criticality {
	SABP_Criticality_reject	= 0,
	SABP_Criticality_ignore	= 1,
	SABP_Criticality_notify	= 2
} e_SABP_Criticality;

/* SABP_Criticality */
typedef long	 SABP_Criticality_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SABP_Criticality;
asn_struct_free_f SABP_Criticality_free;
asn_struct_print_f SABP_Criticality_print;
asn_constr_check_f SABP_Criticality_constraint;
ber_type_decoder_f SABP_Criticality_decode_ber;
der_type_encoder_f SABP_Criticality_encode_der;
xer_type_decoder_f SABP_Criticality_decode_xer;
xer_type_encoder_f SABP_Criticality_encode_xer;
per_type_decoder_f SABP_Criticality_decode_uper;
per_type_encoder_f SABP_Criticality_encode_uper;
per_type_decoder_f SABP_Criticality_decode_aper;
per_type_encoder_f SABP_Criticality_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _SABP_Criticality_H_ */
#include <asn_internal.h>
