/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "SABP-IEs"
 * 	found in "../../asn1/sabp/SABP-IEs.asn"
 * 	`asn1c -R -fcompound-names`
 */

#ifndef	_SABP_Warning_Type_H_
#define	_SABP_Warning_Type_H_


#include <asn_application.h>

/* Including external dependencies */
#include <OCTET_STRING.h>

#ifdef __cplusplus
extern "C" {
#endif

/* SABP_Warning-Type */
typedef OCTET_STRING_t	 SABP_Warning_Type_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SABP_Warning_Type;
asn_struct_free_f SABP_Warning_Type_free;
asn_struct_print_f SABP_Warning_Type_print;
asn_constr_check_f SABP_Warning_Type_constraint;
ber_type_decoder_f SABP_Warning_Type_decode_ber;
der_type_encoder_f SABP_Warning_Type_encode_der;
xer_type_decoder_f SABP_Warning_Type_decode_xer;
xer_type_encoder_f SABP_Warning_Type_encode_xer;
per_type_decoder_f SABP_Warning_Type_decode_uper;
per_type_encoder_f SABP_Warning_Type_encode_uper;
per_type_decoder_f SABP_Warning_Type_decode_aper;
per_type_encoder_f SABP_Warning_Type_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _SABP_Warning_Type_H_ */
#include <asn_internal.h>
