/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "SABP-IEs"
 * 	found in "../../asn1/sabp/SABP-IEs.asn"
 * 	`asn1c -R`
 */

#ifndef	_SABP_Category_H_
#define	_SABP_Category_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum SABP_Category {
	SABP_Category_high_priority	= 0,
	SABP_Category_background_priority	= 1,
	SABP_Category_normal_priority	= 2,
	SABP_Category_default_priority	= 3
	/*
	 * Enumeration is extensible
	 */
} e_SABP_Category;

/* SABP_Category */
typedef long	 SABP_Category_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SABP_Category;
asn_struct_free_f SABP_Category_free;
asn_struct_print_f SABP_Category_print;
asn_constr_check_f SABP_Category_constraint;
ber_type_decoder_f SABP_Category_decode_ber;
der_type_encoder_f SABP_Category_encode_der;
xer_type_decoder_f SABP_Category_decode_xer;
xer_type_encoder_f SABP_Category_encode_xer;
per_type_decoder_f SABP_Category_decode_uper;
per_type_encoder_f SABP_Category_encode_uper;
per_type_decoder_f SABP_Category_decode_aper;
per_type_encoder_f SABP_Category_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _SABP_Category_H_ */
#include <asn_internal.h>
