/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "RUA-IEs"
 * 	found in "../../asn1/rua/RUA-IEs.asn"
 * 	`asn1c -R -fcompound-names`
 */

#ifndef	_RUA_Gsm_map_IDNNS_H_
#define	_RUA_Gsm_map_IDNNS_H_


#include <asn_application.h>

/* Including external dependencies */
#include <BOOLEAN.h>
#include <osmocom/rua/RUA_RoutingParameter.h>
#include <constr_SEQUENCE.h>
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum RUA_Gsm_map_IDNNS__routingbasis_PR {
	RUA_Gsm_map_IDNNS__routingbasis_PR_NOTHING,	/* No components present */
	RUA_Gsm_map_IDNNS__routingbasis_PR_localPTMSI,
	RUA_Gsm_map_IDNNS__routingbasis_PR_tMSIofsamePLMN,
	RUA_Gsm_map_IDNNS__routingbasis_PR_tMSIofdifferentPLMN,
	RUA_Gsm_map_IDNNS__routingbasis_PR_iMSIresponsetopaging,
	RUA_Gsm_map_IDNNS__routingbasis_PR_iMSIcauseUEinitiatedEvent,
	RUA_Gsm_map_IDNNS__routingbasis_PR_iMEI,
	RUA_Gsm_map_IDNNS__routingbasis_PR_spare2,
	RUA_Gsm_map_IDNNS__routingbasis_PR_spare1
} RUA_Gsm_map_IDNNS__routingbasis_PR;

/* RUA_Gsm-map-IDNNS */
typedef struct RUA_Gsm_map_IDNNS {
	struct RUA_Gsm_map_IDNNS__routingbasis {
		RUA_Gsm_map_IDNNS__routingbasis_PR present;
		union RUA_Gsm_map_IDNNS__routingbasis_u {
			struct RUA_Gsm_map_IDNNS__routingbasis__localPTMSI {
				RUA_RoutingParameter_t	 routingparameter;
				
				/* Context for parsing across buffer boundaries */
				asn_struct_ctx_t _asn_ctx;
			} localPTMSI;
			struct RUA_Gsm_map_IDNNS__routingbasis__tMSIofsamePLMN {
				RUA_RoutingParameter_t	 routingparameter;
				
				/* Context for parsing across buffer boundaries */
				asn_struct_ctx_t _asn_ctx;
			} tMSIofsamePLMN;
			struct RUA_Gsm_map_IDNNS__routingbasis__tMSIofdifferentPLMN {
				RUA_RoutingParameter_t	 routingparameter;
				
				/* Context for parsing across buffer boundaries */
				asn_struct_ctx_t _asn_ctx;
			} tMSIofdifferentPLMN;
			struct RUA_Gsm_map_IDNNS__routingbasis__iMSIresponsetopaging {
				RUA_RoutingParameter_t	 routingparameter;
				
				/* Context for parsing across buffer boundaries */
				asn_struct_ctx_t _asn_ctx;
			} iMSIresponsetopaging;
			struct RUA_Gsm_map_IDNNS__routingbasis__iMSIcauseUEinitiatedEvent {
				RUA_RoutingParameter_t	 routingparameter;
				
				/* Context for parsing across buffer boundaries */
				asn_struct_ctx_t _asn_ctx;
			} iMSIcauseUEinitiatedEvent;
			struct RUA_Gsm_map_IDNNS__routingbasis__iMEI {
				RUA_RoutingParameter_t	 routingparameter;
				
				/* Context for parsing across buffer boundaries */
				asn_struct_ctx_t _asn_ctx;
			} iMEI;
			struct RUA_Gsm_map_IDNNS__routingbasis__spare2 {
				RUA_RoutingParameter_t	 routingparameter;
				
				/* Context for parsing across buffer boundaries */
				asn_struct_ctx_t _asn_ctx;
			} spare2;
			struct RUA_Gsm_map_IDNNS__routingbasis__spare1 {
				RUA_RoutingParameter_t	 routingparameter;
				
				/* Context for parsing across buffer boundaries */
				asn_struct_ctx_t _asn_ctx;
			} spare1;
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} routingbasis;
	BOOLEAN_t	 dummy;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} RUA_Gsm_map_IDNNS_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_RUA_Gsm_map_IDNNS;

#ifdef __cplusplus
}
#endif

#endif	/* _RUA_Gsm_map_IDNNS_H_ */
#include <asn_internal.h>
