#pragma once

#define LIBOSMO_RUA_VERSION {{VERSION}}
#define LIBOSMO_RUA_VERSION_STR "{{VERSION}}"

#define LIBOSMO_RUA_VERSION_MAJOR {{VERSION_MAJOR}}
#define LIBOSMO_RUA_VERSION_MINOR {{VERSION_MINOR}}
#define LIBOSMO_RUA_VERSION_PATCH {{VERSION_PATCH}}

#define LIBOSMO_RUA_VERSION_GREATER_EQUAL(major, minor, patch) \
	(LIBOSMO_RUA_VERSION_MAJOR > (major) || \
	 (LIBOSMO_RUA_VERSION_MAJOR == (major) && \
	  LIBOSMO_RUA_VERSION_MINOR > (minor)) || \
	 (LIBOSMO_RUA_VERSION_MAJOR == (major) && \
	  LIBOSMO_RUA_VERSION_MINOR == (minor) && \
	  LIBOSMO_RUA_VERSION_PATCH >= (patch)))
